apiVersion: v1
kind: Service
metadata:
  name:boxeyr
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "boxeyr"
    port: 8080
  selector:
    app: boxeyr
